import { exemple_item } from "../../assets/images/temp";
import { company, people } from "../../assets/svgs";

export const company_live_auctions = [
  {
    live: true,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "company",
    company: "Like",
    end_date: new Date(new Date() + 1000 * 60 * 60 * 24 * 2),
    end_soon: false,
    finis_price: "13",
    hearted: false,
  },
  {
    live: true,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "company",
    company: "Like",
    end_date: new Date(new Date() + 1000 * 60 * 60 * 24 * 2),
    end_soon: false,
    finis_price: "13",
    hearted: false,
  },
  {
    live: true,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "company",
    company: "Like",
    end_date: new Date(new Date() + 1000 * 60 * 60 * 24 * 2),
    end_soon: false,
    finis_price: "13",
    hearted: false,
  },
  {
    live: true,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "company",
    company: "Like",
    end_date: new Date(new Date() + 1000 * 60 * 60 * 24 * 2),
    end_soon: false,
    finis_price: "13",
    hearted: false,
  },
  {
    live: true,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "company",
    company: "Like",
    end_date: new Date(new Date() + 1000 * 60 * 60 * 24 * 2),
    end_soon: false,
    finis_price: "13",
    hearted: false,
  },
  {
    live: true,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "company",
    company: "Like",
    end_date: new Date(new Date() + 1000 * 60 * 60 * 24 * 2),
    end_soon: false,
    finis_price: "13",
    hearted: false,
  },
];

export const individual_live_auctions = [
  {
    live: true,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "",
    end_date: new Date(new Date() + 1000 * 60 * 60 * 24 * 2),
    end_soon: false,
    finis_price: "13",
    hearted: false,
  },
  {
    live: true,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "",
    end_date: new Date(new Date() + 1000 * 60 * 60 * 24 * 2),
    end_soon: false,
    finis_price: "13",
    hearted: false,
  },
  {
    live: true,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "",
    end_date: new Date(new Date() + 1000 * 60 * 60 * 24 * 2),
    end_soon: false,
    finis_price: "13",
    hearted: false,
  },
  {
    live: true,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "company",
    company: "Like",
    end_date: new Date(new Date() + 1000 * 60 * 60 * 24 * 2),
    end_soon: false,
    finis_price: "13",
    hearted: false,
  },
  {
    live: true,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "",
    end_date: new Date(new Date() + 1000 * 60 * 60 * 24 * 2),
    end_soon: false,
    finis_price: "13",
    hearted: false,
  },
  {
    live: true,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "",
    end_date: new Date(new Date() + 1000 * 60 * 60 * 24 * 2),
    end_soon: false,
    finis_price: "13",
    hearted: false,
  },
];

export const types_auctions = [
  {
    title: "Company",
    icon: company,
  },
  {
    title: "Individual",
    icon: people,
  },
];
