import { exemple_item } from "../../assets/images/temp";

export const ending_auctions = [
  {
    live: true,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "company",
    end_date: new Date(new Date() + 1000 * 60 * 2),
    end_soon: true,
    finis_price: "13",
    hearted: false,
  },
  {
    live: true,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "",
    end_date: new Date(new Date() + 1000 * 60 * 2),
    end_soon: true,
    finis_price: "13",
    hearted: false,
  },
  {
    live: true,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "",
    end_date: new Date(new Date() + 1000 * 60 * 2),
    end_soon: true,
    finis_price: "13",
    hearted: false,
  },
  {
    live: true,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "",
    end_date: new Date(new Date() + 1000 * 60 * 2),
    end_soon: true,
    finis_price: "13",
    hearted: false,
  },
  {
    live: true,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "company",
    end_date: new Date(new Date() + 1000 * 60 * 2),
    end_soon: true,
    finis_price: "13",
    hearted: false,
  },
  {
    live: true,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "",
    end_date: new Date(new Date() + 1000 * 60 * 2),
    end_soon: true,
    finis_price: "13",
    hearted: false,
  },
  {
    live: true,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "",
    end_date: new Date(new Date() + 1000 * 60 * 2),
    end_soon: true,
    finis_price: "13",
    hearted: false,
  },
  {
    live: true,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "",
    end_date: new Date(new Date() + 1000 * 60 * 2),
    end_soon: true,
    finis_price: "13",
    hearted: false,
  },
  {
    live: true,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "company",
    end_date: new Date(new Date() + 1000 * 60 * 2),
    end_soon: true,
    finis_price: "13",
    hearted: false,
  },
  {
    live: true,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "",
    end_date: new Date(new Date() + 1000 * 60 * 2),
    end_soon: true,
    finis_price: "13",
    hearted: false,
  },
  {
    live: true,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "",
    end_date: new Date(new Date() + 1000 * 60 * 2),
    end_soon: true,
    finis_price: "13",
    hearted: false,
  },
  {
    live: true,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "",
    end_date: new Date(new Date() + 1000 * 60 * 2),
    end_soon: true,
    finis_price: "13",
    hearted: false,
  },
  {
    live: true,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "company",
    end_date: new Date(new Date() + 1000 * 60 * 2),
    end_soon: true,
    finis_price: "13",
    hearted: false,
  },
  {
    live: true,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "",
    end_date: new Date(new Date() + 1000 * 60 * 2),
    end_soon: true,
    finis_price: "13",
    hearted: false,
  },
  {
    live: true,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "",
    end_date: new Date(new Date() + 1000 * 60 * 2),
    end_soon: true,
    finis_price: "13",
    hearted: false,
  },
  {
    live: true,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "",
    end_date: new Date(new Date() + 1000 * 60 * 2),
    end_soon: true,
    finis_price: "13",
    hearted: false,
  },
];
