import { exemple_item } from "../../assets/images/temp";

export const list_auctions = [
  "All auctions",
  "Bet Auctions",
  "Good",
  "Appel",
  "Smartphones",
  "House & Garden",
  "Video games",
  "Beauty",
  "Home applicationces",
  "Kitchen",
  "Hobby",
  "TV and Audio",
  // danger is here
  "Fashion",
  "Sport",
  "Jewellery",
  "Watches",
  "Cars",
  "Motorcycles",
  "Boats",
  "Real Estate",
  "Other",
];

export const live_auctions = [
  {
    live: true,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "company",
    end_date: new Date(new Date() + 1000 * 60 * 60 * 24 * 2),
    end_soon: false,
    finis_price: "13",
    hearted: false,
  },
  {
    live: true,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "",
    end_date: new Date(new Date() + 1000 * 60 * 60 * 24 * 2),
    end_soon: false,
    finis_price: "13",
    hearted: false,
  },
  {
    live: true,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "",
    end_date: new Date(new Date() + 1000 * 60 * 60 * 24 * 2),
    end_soon: false,
    finis_price: "13",
    hearted: false,
  },
  {
    live: true,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "",
    end_date: new Date(new Date() + 1000 * 60 * 60 * 24 * 2),
    end_soon: false,
    finis_price: "13",
    hearted: false,
  },
];

export const ending_soon = [
  {
    live: true,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "company",
    end_date: new Date(new Date() + 1000 * 60 * 2),
    end_soon: true,
    finis_price: "13",
    hearted: false,
  },
  {
    live: true,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "",
    end_date: new Date(new Date() + 1000 * 60 * 2),
    end_soon: true,
    finis_price: "13",
    hearted: false,
  },
  {
    live: true,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "",
    end_date: new Date(new Date() + 1000 * 60 * 2),
    end_soon: true,
    finis_price: "13",
    hearted: false,
  },
  {
    live: true,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "",
    end_date: new Date(new Date() + 1000 * 60 * 2),
    end_soon: true,
    finis_price: "13",
    hearted: false,
  },
];

export const finished_auctions = [
  {
    live: false,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "company",
    end_date: new Date(new Date() - 1000 * 60 * 2),
    end_soon: false,
    finis_price: "13",
    hearted: false,
  },
  {
    live: false,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "",
    end_date: new Date(new Date() - 1000 * 60 * 2),
    end_soon: false,
    finis_price: "13",
    hearted: false,
  },
  {
    live: false,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "",
    end_date: new Date(new Date() - 1000 * 60 * 2),
    end_soon: false,
    finis_price: "13",
    hearted: false,
  },
  {
    live: false,
    img: exemple_item,
    title: "Sony ZX330BT",
    price: "35.00",
    name_bid: "George",
    starting_price: "1.77",
    with_icon: "",
    end_date: new Date(new Date() - 1000 * 60 * 2),
    end_soon: false,
    finis_price: "13",
    hearted: false,
  },
];
